package net.querix.paper.gui

@Deprecated("old, bad solution, but a lot of systems depend on it")
enum class Slots {
    RowOneSlotOne,
    RowOneSlotTwo,
    RowOneSlotThree,
    RowOneSlotFour,
    RowOneSlotFive,
    RowOneSlotSix,
    RowOneSlotSeven,
    RowOneSlotEight,
    RowOneSlotNine,

    RowTwoSlotOne,
    RowTwoSlotTwo,
    RowTwoSlotThree,
    RowTwoSlotFour,
    RowTwoSlotFive,
    RowTwoSlotSix,
    RowTwoSlotSeven,
    RowTwoSlotEight,
    RowTwoSlotNine,

    RowThreeSlotOne,
    RowThreeSlotTwo,
    RowThreeSlotThree,
    RowThreeSlotFour,
    RowThreeSlotFive,
    RowThreeSlotSix,
    RowThreeSlotSeven,
    RowThreeSlotEight,
    RowThreeSlotNine,

    RowFourSlotOne,
    RowFourSlotTwo,
    RowFourSlotThree,
    RowFourSlotFour,
    RowFourSlotFive,
    RowFourSlotSix,
    RowFourSlotSeven,
    RowFourSlotEight,
    RowFourSlotNine,

    RowFiveSlotOne,
    RowFiveSlotTwo,
    RowFiveSlotThree,
    RowFiveSlotFour,
    RowFiveSlotFive,
    RowFiveSlotSix,
    RowFiveSlotSeven,
    RowFiveSlotEight,
    RowFiveSlotNine,

    RowSixSlotOne,
    RowSixSlotTwo,
    RowSixSlotThree,
    RowSixSlotFour,
    RowSixSlotFive,
    RowSixSlotSix,
    RowSixSlotSeven,
    RowSixSlotEight,
    RowSixSlotNine,
}